import { QUESTS, BOSSES, BOSS_TYPES, SOURCES, HEROES, SLOTS, TYPES, QUALITIES, STATS } from './types'

export const items = [

  // PROVING_YOUR_WORTH
  {
    name: 'Vormur Battle Quiver',
    desc: 'PEW PEW!',
    slot: SLOTS.OFFHAND,
    type: TYPES.QUIVER,
    level: 8,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.QUEST,
      id: QUESTS.PROVING_YOUR_WORTH
    },
    stats: {
      [STATS.ATTACK_POWER]: 11,
      [STATS.ATTACK_CRIT_CHANCE]: 0.59,
      [STATS.ATTACK_CRIT_POWER]: 2.77,
    }
  },
  {
    name: 'Vormur Battle Shield',
    desc: 'Fierce looking, sturdy, large, easy to use... and oh so heavy!',
    slot: SLOTS.OFFHAND,
    type: TYPES.SHIELD,
    level: 8,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.QUEST,
      id: QUESTS.PROVING_YOUR_WORTH
    },
    stats: {
      [STATS.ARMOR]: 5,
      [STATS.LIFE]: 8,
      [STATS.BLOCK]: 2.24,
    }
  },
  {
    name: 'Vormur Divine Ledger',
    desc: 'A holy book said to be able to help protect the protectors... If that makes any sense.',
    slot: SLOTS.OFFHAND,
    type: TYPES.BOOK,
    level: 8,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.QUEST,
      id: QUESTS.PROVING_YOUR_WORTH
    },
    stats: {
      [STATS.SPELL_POWER]: 10,
      [STATS.LIFE]: 8,
      [STATS.MANA_REGEN]: 0.12,
    }
  },
  {
    name: 'Vormur Energy Wand',
    desc: 'No spell user is complete without their wand!',
    slot: SLOTS.OFFHAND,
    type: TYPES.WAND,
    level: 8,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.QUEST,
      id: QUESTS.PROVING_YOUR_WORTH
    },
    stats: {
      [STATS.SPELL_POWER]: 10,
      [STATS.SPELL_CRIT_CHANCE]: 0.59,
      [STATS.SPELL_CRIT_POWER]: 2.77,
    }
  },
  {
    name: 'Vormur Storm Shield',
    desc: 'A decorated shield used by the best warriors of Vormur.',
    slot: SLOTS.OFFHAND,
    type: TYPES.SHIELD,
    level: 8,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.QUEST,
      id: QUESTS.PROVING_YOUR_WORTH
    },
    stats: {
      [STATS.ARMOR]: 5,
      [STATS.LIFE]: 8,
      [STATS.BLOCK]: 2.24,
    }
  },
  {
    name: 'Vormur Shanker',
    desc: 'A fine crafted dagger used by the rogues of Vormur.',
    slot: SLOTS.OFFHAND,
    type: TYPES.SHIELD,
    level: 8,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.QUEST,
      id: QUESTS.PROVING_YOUR_WORTH
    },
    stats: {
      [STATS.ATTACK_POWER]: 11,
      [STATS.SPELL_POWER]: 3,
      [STATS.ATTACK_CRIT_CHANCE]: 0.59,
      [STATS.ATTACK_CRIT_POWER]: 2.77,
    }
  },
  {
    name: 'Vormur Battle Axe',
    desc: '',
    slot: SLOTS.OFFHAND,
    type: TYPES.DUAL_AXE,
    level: 8,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.QUEST,
      id: QUESTS.PROVING_YOUR_WORTH
    },
    stats: {
      [STATS.ATTACK_POWER]: 11,
      [STATS.ATTACK_CRIT_CHANCE]: 0.59,
      [STATS.ATTACK_CRIT_POWER]: 2.77,
    }
  },
  {
    name: 'Vormur Wild Idol',
    desc: '',
    slot: SLOTS.OFFHAND,
    type: TYPES.IDOL,
    level: 8,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.QUEST,
      id: QUESTS.PROVING_YOUR_WORTH
    },
    stats: {
      [STATS.POWER]: 6,
      [STATS.AGILITY]: 6,
      [STATS.ENERGY]: 5,
    }
  },

  // BROODMOTHER
  {
    name: 'Broodmother\'s Web',
    desc: 'It\'s sticky...',
    slot: SLOTS.NECK,
    type: TYPES.ACCESSORY,
    level: 8,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.BROODMOTHER,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.ENERGY]: 6,
      [STATS.ATTACK_POWER]: 9,
      [STATS.SPELL_POWER]: 7,
      [STATS.MANA]: 14,
      [STATS.MANA_REGEN]: 0.25,
    }
  },
  {
    name: 'Broodmother\'s Mandible',
    desc: '... Yuck!',
    slot: SLOTS.NECK,
    type: TYPES.ACCESSORY,
    level: 8,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.BROODMOTHER,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.POWER]: 6,
      [STATS.ARMOR]: 10,
      [STATS.LIFE]: 14,
      [STATS.BLOCK]: 3.88,
    }
  },
  {
    name: 'Vormur Archmage Signet',
    desc: '',
    slot: SLOTS.RING,
    type: TYPES.ACCESSORY,
    level: 8,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.BROODMOTHER,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.SPELL_POWER]: 10,
      [STATS.MANA]: 14,
      [STATS.MANA_REGEN]: 0.25,
    }
  },
  {
    name: 'Vormur Fighter Signet',
    desc: '',
    slot: SLOTS.RING,
    type: TYPES.ACCESSORY,
    level: 8,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.BROODMOTHER,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.AGILITY]: 6,
      [STATS.ATTACK_POWER]: 12,
      [STATS.LIFE]: 16,
    }
  },
  {
    name: 'Breeches of the Brood',
    desc: 'The Brood has you!',
    slot: SLOTS.LEGS,
    type: TYPES.MITHRIL,
    level: 14,
    quality: QUALITIES.RELIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.BROODMOTHER,
      kill: BOSS_TYPES.UVX,
    },
    stats: {
      [STATS.DAMAGE]: 25,
      [STATS.ATTACK_SPEED]: 13.43,
      [STATS.LIFE]: -22,
      [STATS.MANA]: -11,
      [STATS.MOVE_SPEED]: -15,
      [STATS.ATTACK_POWER]: 12,
      [STATS.SPELL_POWER]: 18,
    },
    special: {
      [HEROES.BARBARIAN]: 'Deep Slice\'s cooldown is lowered to 1.35 seconds but its mana cost is increased.',
      [HEROES.CLERIC]: 'Divine Protection no longer reduces damage taken but instead heals target for 0.2 * Spell Power per second. (Effect stacks with Blind Faith/Perfect Devotion\'s healing.',
      [HEROES.PALADIN]: 'Mark of Sanctuary reduces 5% more damage.',
    }
  },
  {
    name: 'Arachnid Straps',
    desc: 'It\'s made from Broodmother\'s silk. Strange magic flows around it...',
    slot: SLOTS.BELT,
    type: TYPES.MITHRIL,
    level: 14,
    quality: QUALITIES.RELIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.BROODMOTHER,
      kill: BOSS_TYPES.UVX,
    },
    stats: {
      [STATS.MANA]: 25,
      [STATS.MOVE_SPEED]: -15,
      [STATS.ATTACK_CRIT_CHANCE]: 2.98,
      [STATS.ATTACK_CRIT_POWER]: 17.06,
      [STATS.SPELL_CRIT_CHANCE]: 2.98,
      [STATS.SPELL_CRIT_POWER]: 17.06,
      [STATS.MAGIC_RESIST]: 0.76,
    },
    special: {
      [HEROES.EARTHQUAKER]: 'Totem Strike\'s cooldown is reduced to 10 seconds.',
      [HEROES.SHADOW_SHAMAN]: 'Increase Bloodthirst\'s duration by 50% and effect by 1.5x.',
    }
  },

  // NARITH
  {
    name: 'Painwalker Treads',
    desc: '',
    slot: SLOTS.BOOTS,
    type: TYPES.LEATHER,
    level: 14,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NARITH,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.AGILITY]: 3,
      [STATS.ATTACK_POWER]: 5,
      [STATS.SPELL_POWER]: 5,
      [STATS.ATTACK_CRIT_CHANCE]: 1.03,
      [STATS.ATTACK_CRIT_POWER]: 4.85,
      [STATS.ARMOR]: 2,
      [STATS.MOVE_SPEED]: 13,
      [STATS.MAGIC_RESIST]: 0.50,
    }
  },
  {
    name: 'Eversilk Slippers',
    desc: '',
    slot: SLOTS.BOOTS,
    type: TYPES.CLOTH,
    level: 14,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NARITH,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.ENERGY]: 3,
      [STATS.SPELL_POWER]: 5,
      [STATS.ARMOR]: 1,
      [STATS.LIFE]: 15,
      [STATS.MANA_REGEN]: 0.22,
      [STATS.MOVE_SPEED]: 13,
    }
  },
  {
    name: 'Neversilk Slippers',
    desc: '',
    slot: SLOTS.BOOTS,
    type: TYPES.CLOTH,
    level: 14,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NARITH,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.ENERGY]: 3,
      [STATS.SPELL_POWER]: 5,
      [STATS.SPELL_CRIT_CHANCE]: 1.03,
      [STATS.SPELL_CRIT_POWER]: 4.85,
      [STATS.ARMOR]: 1,
      [STATS.MOVE_SPEED]: 13,
    }
  },
  {
    name: 'Protector\'s Greaves',
    desc: '',
    slot: SLOTS.BOOTS,
    type: TYPES.MAIL,
    level: 14,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NARITH,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.POWER]: 3,
      [STATS.ATTACK_POWER]: 5,
      [STATS.ARMOR]: 2,
      [STATS.LIFE]: 15,
      [STATS.MOVE_SPEED]: 13,
      [STATS.DODGE]: 0.98,
      [STATS.MAGIC_RESIST]: 0.84,
    }
  },
  {
    name: 'Powerwalker Treads',
    desc: '',
    slot: SLOTS.BOOTS,
    type: TYPES.MAIL,
    level: 14,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NARITH,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.POWER]: 3,
      [STATS.ENERGY]: 3,
      [STATS.ATTACK_POWER]: 5,
      [STATS.SPELL_POWER]: 5,
      [STATS.ARMOR]: 2,
      [STATS.LIFE]: 15,
      [STATS.MOVE_SPEED]: 13,
      [STATS.MAGIC_RESIST]: 0.84,
    }
  },
  {
    name: 'Forestwalker Treads',
    desc: '',
    slot: SLOTS.BOOTS,
    type: TYPES.LEATHER,
    level: 14,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NARITH,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.ENERGY]: 4,
      [STATS.ATTACK_POWER]: 5,
      [STATS.SPELL_POWER]: 5,
      [STATS.ARMOR]: 2,
      [STATS.LIFE]: 15,
      [STATS.MOVE_SPEED]: 13,
      [STATS.MAGIC_RESIST]: 0.50,
    }
  },
  {
    name: 'Blade of the Fallen',
    desc: '',
    slot: SLOTS.MAINHAND,
    type: TYPES.SWORD,
    level: 14,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NARITH,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.POWER]: 4,
      [STATS.ATTACK_POWER]: 13,
      [STATS.SPELL_POWER]: 4,
      [STATS.ATTACK_CRIT_CHANCE]: 1.13,
      [STATS.DAMAGE]: 18,
      [STATS.ATTACK_SPEED]: 5.08,
    }
  },
  {
    name: 'Bow of the Fallen',
    desc: '',
    slot: SLOTS.MAINHAND,
    type: TYPES.BOW,
    level: 14,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NARITH,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.AGILITY]: 4,
      [STATS.ATTACK_POWER]: 13,
      [STATS.ATTACK_CRIT_CHANCE]: 1.13,
      [STATS.DAMAGE]: 18,
      [STATS.ATTACK_SPEED]: 5.08,
    }
  },
  {
    name: 'Dagger of the Fallen',
    desc: '',
    slot: SLOTS.MAINHAND,
    type: TYPES.DAGGER,
    level: 14,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NARITH,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.AGILITY]: 4,
      [STATS.ATTACK_POWER]: 13,
      [STATS.SPELL_POWER]: 2,
      [STATS.ATTACK_CRIT_CHANCE]: 1.13,
      [STATS.DAMAGE]: 18,
      [STATS.ATTACK_SPEED]: 5.08,
    }
  },
  {
    name: 'Staff of the Fallen',
    desc: '',
    slot: SLOTS.MAINHAND,
    type: TYPES.STAFF,
    level: 14,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NARITH,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.ENERGY]: 3,
      [STATS.ATTACK_POWER]: 4,
      [STATS.SPELL_POWER]: 12,
      [STATS.SPELL_CRIT_CHANCE]: 1.13,
      [STATS.DAMAGE]: 18,
      [STATS.MANA_REGEN]: 0.22,
    }
  },
  {
    name: 'Mace of the Fallen',
    desc: '',
    slot: SLOTS.MAINHAND,
    type: TYPES.MACE,
    level: 14,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NARITH,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.POWER]: 3,
      [STATS.ENERGY]: 3,
      [STATS.ATTACK_POWER]: 2,
      [STATS.SPELL_POWER]: 7,
      [STATS.DAMAGE]: 18,
      [STATS.MANA]: 25,
      [STATS.MANA_REGEN]: 0.22,
    }
  },
  {
    name: 'Axe of the Fallen',
    desc: '',
    slot: SLOTS.MAINHAND,
    type: TYPES.AXE,
    level: 14,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NARITH,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.POWER]: 3,
      [STATS.ATTACK_POWER]: 7,
      [STATS.ATTACK_CRIT_CHANCE]: 1.13,
      [STATS.ATTACK_CRIT_POWER]: 5.34,
      [STATS.DAMAGE]: 18,
      [STATS.ATTACK_SPEED]: 5.08,
    }
  },
  {
    name: 'Lucky Star',
    desc: 'Add some luck in your life.',
    slot: SLOTS.NECK,
    type: TYPES.ACCESSORY,
    level: 20,
    quality: QUALITIES.RELIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NARITH,
      kill: BOSS_TYPES.UVX,
    },
    stats: {
      [STATS.ATTACK_CRIT_CHANCE]: 3.73,
      [STATS.SPELL_CRIT_CHANCE]: 3.73,
      [STATS.ATTACK_CRIT_POWER]: 21.33,
      [STATS.SPELL_CRIT_POWER]: 21.33,
      [STATS.GOLD]: 9.75,
      [STATS.EXP]: 9.75,
    },
    special: {
      [HEROES.ALL]: 'Adds +35 to Luck. Luck stat grants you a small chance to obtain extra Epic and Relic drops and increases Primal Flame, Fate Card, and Divine Carnelia drop rate by 1%.'
    }
  },
  {
    name: 'Boggart\'s Bloomers',
    desc: 'Silently but surely, boggarts return order.',
    slot: SLOTS.BOOTS,
    type: TYPES.MITHRIL,
    level: 20,
    quality: QUALITIES.RELIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NARITH,
      kill: BOSS_TYPES.UVX,
    },
    stats: {
      [STATS.ATTACK_CRIT_POWER]: 12.25,
      [STATS.SPELL_CRIT_POWER]: 9.14,
      [STATS.MOVE_SPEED]: 18,
      [STATS.ARMOR]: 4,
      [STATS.LIFE]: -40,
      [STATS.MANA]: -22,
      [STATS.LIFE_REGEN]: -4.15,
      [STATS.MANA_REGEN]: -0.47,
    },
    special: {
      [HEROES.ARCANIST]: 'Every skill cast will now return 33% of its manacost after the cast.',
      [HEROES.MEDICASTER]: '15% of all healing dealt on allies will heal the caster.',
      [HEROES.CHRONOWARPER]: 'Dimension Slash procs during Astral Form consume 50% less mana.',
    }
  },
  {
    name: 'Charmed Hasty Handwraps',
    desc: 'The best of unholy magic.',
    slot: SLOTS.GLOVES,
    type: TYPES.MITHRIL,
    level: 20,
    quality: QUALITIES.RELIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NARITH,
      kill: BOSS_TYPES.UVX,
    },
    stats: {
      [STATS.POWER]: -3,
      [STATS.ENERGY]: 7,
      [STATS.ARMOR]: 13,
      [STATS.ATTACK_POWER]: 15,
      [STATS.SPELL_POWER]: -8,
      [STATS.MANA_REGEN]: 0.35,
    },
    special: {
      [HEROES.DRUID]: 'Rejuvenation cooldown is lowered to 3 seconds but its mana cost is increased and its effectiveness is reduced by 50%.',
      [HEROES.CHAOTIC_KNIGHT]: 'Heals allies in 150 AoE (including self) for 67% of healing done to primary target.',
      [HEROES.SHADOWBLADE]: 'Time Strike restores half of its mana cost.',
    }
  },
  {
    name: 'Spelled Claws of Undying',
    desc: 'Make your foe fear you.',
    slot: SLOTS.GLOVES,
    type: TYPES.MITHRIL,
    level: 20,
    quality: QUALITIES.RELIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NARITH,
      kill: BOSS_TYPES.UVX,
    },
    stats: {
      [STATS.LIFE_REGEN]: 3.33,
      [STATS.MANA_REGEN]: -0.11,
      [STATS.ATTACK_POWER]: -7,
      [STATS.SPELL_POWER]: -5,
      [STATS.ATTACK_CRIT_CHANCE]: 2.25,
      [STATS.ATTACK_CRIT_POWER]: 11.94,
      [STATS.SPELL_CRIT_CHANCE]: 2.25,
      [STATS.SPELL_CRIT_POWER]: 11.94,
    },
    special: {
      [HEROES.HYDROMANCER]: 'Increases Purify\'s damage by (2.5 * Hero Level)%',
      [HEROES.PYROMANCER]: 'Increases Dragon Breath\'s damage by (2.5 * Hero Level)%',
      [HEROES.VENOMANCER]: 'Increases Emerald Rose\'s damage by (2.5 * Hero Level)%',
    }
  },
  {
    name: 'Robe of Death',
    desc: 'Shroud of a fallen angel.',
    slot: SLOTS.CHEST,
    type: TYPES.CLOTH,
    level: 20,
    quality: QUALITIES.RELIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NARITH,
      kill: BOSS_TYPES.UVX,
    },
    stats: {
      [STATS.POWER]: 12,
      [STATS.AGILITY]: 12,
      [STATS.ENERGY]: 17,
      [STATS.ARMOR]: 15,
      [STATS.LIFE_REGEN]: 6.67,
      [STATS.MANA_REGEN]: 0.44,
      [STATS.MAGIC_RESIST]: 0.96,
    },
    special: {
      [HEROES.AEROMANCER]: 'Blitz consumes less mana. Reduce Blitz cooldown to 0.5 seconds.',
    }
  },

  // SAND GOLEM
  {
    name: 'Plated Leggings of the Sun',
    desc: '',
    slot: SLOTS.LEGS,
    type: TYPES.MAIL,
    level: 18,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.SAND_GOLEM,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.POWER]: 4,
      [STATS.ATTACK_POWER]: 6,
      [STATS.SPELL_POWER]: 2,
      [STATS.ARMOR]: 11,
      [STATS.LIFE]: 22,
      [STATS.MAGIC_RESIST]: 1.07,
    }
  },
  {
    name: 'Plated Leggings of the Sand',
    desc: '',
    slot: SLOTS.LEGS,
    type: TYPES.MAIL,
    level: 18,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.SAND_GOLEM,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.POWER]: 4,
      [STATS.ATTACK_POWER]: 8,
      [STATS.SPELL_POWER]: 2,
      [STATS.ATTACK_CRIT_CHANCE]: 1.05,
      [STATS.ATTACK_CRIT_POWER]: 7.41,
      [STATS.ARMOR]: 5,
      [STATS.MAGIC_RESIST]: 1.07,
    }
  },
  {
    name: 'Divine Winged Helm of the Sun',
    desc: '',
    slot: SLOTS.HELM,
    type: TYPES.MAIL,
    level: 18,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.SAND_GOLEM,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.ENERGY]: 3,
      [STATS.ATTACK_POWER]: 4,
      [STATS.SPELL_POWER]: 11,
      [STATS.ARMOR]: 4,
      [STATS.LIFE]: 28,
      [STATS.MANA_REGEN]: 0.13,
      [STATS.MAGIC_RESIST]: 1.07,
    }
  },
  {
    name: 'Golden Gauntlets of the Sand',
    desc: '',
    slot: SLOTS.GLOVES,
    type: TYPES.LEATHER,
    level: 18,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.SAND_GOLEM,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.AGILITY]: 4,
      [STATS.ATTACK_POWER]: 9,
      [STATS.SPELL_POWER]: 3,
      [STATS.ATTACK_CRIT_CHANCE]: 1.05,
      [STATS.ATTACK_CRIT_POWER]: 6.79,
      [STATS.ARMOR]: 2,
      [STATS.MAGIC_RESIST]: 0.64,
    }
  },
  {
    name: 'Golden Gauntlets of the Sun',
    desc: '',
    slot: SLOTS.GLOVES,
    type: TYPES.LEATHER,
    level: 18,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.SAND_GOLEM,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.ENERGY]: 3,
      [STATS.ATTACK_POWER]: 4,
      [STATS.SPELL_POWER]: 11,
      [STATS.ARMOR]: 2,
      [STATS.LIFE]: 28,
      [STATS.MANA_REGEN]: 0.13,
      [STATS.MAGIC_RESIST]: 0.64,
    }
  },
  {
    name: 'Weaver\'s Mantle of the Sun',
    desc: '',
    slot: SLOTS.SHOULDER,
    type: TYPES.CLOTH,
    level: 18,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.SAND_GOLEM,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.ENERGY]: 3,
      [STATS.SPELL_POWER]: 9,
      [STATS.SPELL_CRIT_CHANCE]: 1.11,
      [STATS.SPELL_CRIT_POWER]: 9.57,
      [STATS.ARMOR]: 2,
    }
  },
  {
    name: 'Divine Mantle of the Sun',
    desc: '',
    slot: SLOTS.SHOULDER,
    type: TYPES.CLOTH,
    level: 18,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.SAND_GOLEM,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.ENERGY]: 3,
      [STATS.SPELL_POWER]: 11,
      [STATS.ARMOR]: 2,
      [STATS.LIFE]: 28,
      [STATS.MANA_REGEN]: 0.13,
    }
  },
  {
    name: 'Sandstone Helm of the Desert',
    desc: '',
    slot: SLOTS.HELM,
    type: TYPES.MAIL,
    level: 18,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.SAND_GOLEM,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.POWER]: 9,
      [STATS.ARMOR]: 12,
      [STATS.LIFE_REGEN]: 2.94,
      [STATS.MAGIC_RESIST]: 1.07,
    }
  },
  {
    name: 'Sun Blanched Helm of the Desert',
    desc: '',
    slot: SLOTS.HELM,
    type: TYPES.LEATHER,
    level: 18,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.SAND_GOLEM,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.AGILITY]: 8,
      [STATS.ATTACK_POWER]: 4,
      [STATS.SPELL_POWER]: 1,
      [STATS.ATTACK_SPEED]: 16.17,
      [STATS.ARMOR]: 3,
      [STATS.DODGE]: 1.30,
      [STATS.MAGIC_RESIST]: 0.64,
    }
  },
  {
    name: 'Sandsilk Cap of the Desert',
    desc: '',
    slot: SLOTS.HELM,
    type: TYPES.CLOTH,
    level: 18,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.SAND_GOLEM,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.SPELL_POWER]: 17,
      [STATS.SPELL_CRIT_POWER]: 10.19,
      [STATS.ARMOR]: 3,
      [STATS.MANA]: 50,
    }
  },
  {
    name: 'Polished Golden Necklace',
    desc: '',
    slot: SLOTS.NECK,
    type: TYPES.ACCESSORY,
    level: 18,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.SAND_GOLEM,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.LIFE]: 49,
      [STATS.MANA]: 41,
      [STATS.MANA_REGEN]: 1.22,
    }
  },
  {
    name: 'Rough Golden Necklace',
    desc: '',
    slot: SLOTS.NECK,
    type: TYPES.ACCESSORY,
    level: 18,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.SAND_GOLEM,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.ATTACK_POWER]: 32,
      [STATS.SPELL_POWER]: 22,
      [STATS.DAMAGE]: 3,
      [STATS.LIFE]: 19,
      [STATS.DODGE]: 0.69,
    }
  },
  {
    name: 'Jagged Necklace of Peril',
    desc: '',
    slot: SLOTS.NECK,
    type: TYPES.ACCESSORY,
    level: 18,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.SAND_GOLEM,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.ATTACK_CRIT_CHANCE]: 3.96,
      [STATS.ATTACK_CRIT_POWER]: 18.68,
      [STATS.SPELL_CRIT_CHANCE]: 3.96,
      [STATS.SPELL_CRIT_POWER]: 18.68,
      [STATS.MOVE_SPEED]: 7,
    }
  },
  {
    name: 'Sober Guard',
    desc: 'Stand strong and calm in any state of your innards.',
    slot: SLOTS.BOOTS,
    type: TYPES.MITHRIL,
    level: 24,
    quality: QUALITIES.RELIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.SAND_GOLEM,
      kill: BOSS_TYPES.UVX,
    },
    stats: {
      [STATS.POWER]: 33,
      [STATS.MOVE_SPEED]: 21,
    },
    special: {
      [HEROES.ALL]: 'Reduces the duration of stuns to 0.1 seconds.'
    }
  },
  {
    name: 'Sandy Basher',
    desc: 'If they disagree, bash their heads!',
    slot: SLOTS.MAINHAND,
    type: TYPES.STAFF,
    level: 24,
    quality: QUALITIES.RELIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.SAND_GOLEM,
      kill: BOSS_TYPES.UVX,
    },
    stats: {
      [STATS.SPELL_POWER]: 30,
      [STATS.ATTACK_SPEED]: 33.27,
      [STATS.ARMOR]: 22,
    },
    special: {
      [HEROES.CLERIC]: 'Attack has 10% chance to stun target for 2 seconds. If the target is a boss, its attack speed is lowered by 25% for 2 seconds.',
      [HEROES.DRUID]: 'Bear\'s Hibernate triggers its effect after 2.5 seconds instead of 5 seconds.'
    }
  },
  {
    name: 'Desert Jewel',
    desc: 'The prize of the desert, shrouded in sand.',
    slot: SLOTS.NECK,
    type: TYPES.ACCESSORY,
    level: 24,
    quality: QUALITIES.RELIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.SAND_GOLEM,
      kill: BOSS_TYPES.UVX,
    },
    stats: {
      [STATS.AGILITY]: 20,
      [STATS.ARMOR]: 35,
      [STATS.LIFE]: 88,
      [STATS.MANA]: 108,
    },
    special: {
      [HEROES.CHAOTIC_KNIGHT]: 'Improved Armor Break will now increase physical damage taken by an amount equal to the magic resistance penalty. Increase magic resistance penalty to 1.3x.',
      [HEROES.EARTHQUAKER]: 'Ember Strike applies the Improved Heavystrike debuff. Increase Improved Heavystrike\'s effect by 50% (multiplicative).'
    }
  },

  // NAZTAR
  {
    name: 'Charger\'s Boots',
    desc: '',
    slot: SLOTS.BOOTS,
    type: TYPES.MAIL,
    level: 21,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NAZTAR,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.MAGIC_RESIST]: 1.22,
      [STATS.ARMOR]: 3,
      [STATS.MOVE_SPEED]: 32,
      [STATS.POWER]: 6,
    },
  },
  {
    name: 'Boots of Striding and Springing',
    desc: '',
    slot: SLOTS.BOOTS,
    type: TYPES.LEATHER,
    level: 21,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NAZTAR,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.MAGIC_RESIST]: 0.73,
      [STATS.ARMOR]: 2,
      [STATS.MOVE_SPEED]: 32,
      [STATS.AGILITY]: 4,
    },
  },
  {
    name: 'Boots of Expeditous Retreat',
    desc: '',
    slot: SLOTS.BOOTS,
    type: TYPES.CLOTH,
    level: 21,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NAZTAR,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.ARMOR]: 2,
      [STATS.MOVE_SPEED]: 32,
      [STATS.ENERGY]: 8,
    },
  },
  {
    name: 'Ring of the Heavens',
    desc: '',
    slot: SLOTS.RING,
    type: TYPES.ACCESSORY,
    level: 21,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NAZTAR,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.POWER]: 12,
      [STATS.AGILITY]: 12,
      [STATS.ENERGY]: 14,
    },
  },
  {
    name: 'Ring of Barrier',
    desc: 'Free barriers for everybody!',
    slot: SLOTS.RING,
    type: TYPES.ACCESSORY,
    level: 30,
    quality: QUALITIES.RELIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.NAZTAR,
      kill: BOSS_TYPES.UVX,
    },
    stats: {
      [STATS.POWER]: 20,
      [STATS.AGILITY]: 20,
      [STATS.ENERGY]: 20,
    },
    special: {
      [HEROES.ALL]: 'Creates a Magical Shield once every 30 seconds automatically to protect the hero. The amount of blocked damage is equal to 500+20% of all players\' current mana, to a limit of 1350. The shield cannot be stacked. The shield does not conflict with other types of barriers. The 30 second cooldown only starts counting once the shield breaks.'
    }
  },

  // KARRIX
  {
    name: 'Defender\'s Girdle',
    desc: '',
    slot: SLOTS.BELT,
    type: TYPES.MAIL,
    level: 23,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.SPELL_POWER]: 2,
      [STATS.MAGIC_RESIST]: 1.32,
      [STATS.ARMOR]: 10,
      [STATS.POWER]: 5,
      [STATS.LIFE]: 28,
      [STATS.ATTACK_POWER]: 8,
    },
  },
  {
    name: 'Gloves of Wrath',
    desc: '',
    slot: SLOTS.GLOVES,
    type: TYPES.MAIL,
    level: 23,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.ATTACK_CRIT_POWER]: 9.11,
      [STATS.SPELL_POWER]: 3,
      [STATS.MAGIC_RESIST]: 1.32,
      [STATS.ARMOR]: 3,
      [STATS.POWER]: 5,
      [STATS.ATTACK_POWER]: 10,
      [STATS.ATTACK_CRIT_CHANCE]: 1.29,
    },
  },
  {
    name: 'Consecrated Breastplate',
    desc: '',
    slot: SLOTS.CHEST,
    type: TYPES.MAIL,
    level: 23,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.SPELL_POWER]: 14,
      [STATS.MAGIC_RESIST]: 1.32,
      [STATS.MANA_REGEN]: 0.16,
      [STATS.ARMOR]: 8,
      [STATS.LIFE]: 35,
      [STATS.ATTACK_POWER]: 5,
      [STATS.ENERGY]: 3,
    },
  },
  {
    name: 'Spaulders of Nature\'s Wrath',
    desc: '',
    slot: SLOTS.CHEST,
    type: TYPES.LEATHER,
    level: 23,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.ATTACK_CRIT_POWER]: 8.35,
      [STATS.SPELL_POWER]: 3,
      [STATS.MAGIC_RESIST]: 0.79,
      [STATS.ARMOR]: 7,
      [STATS.ATTACK_POWER]: 11,
      [STATS.AGILITY]: 5,
      [STATS.ATTACK_CRIT_CHANCE]: 1.29,
    },
  },
  {
    name: 'Peaceful Pelisse',
    desc: '',
    slot: SLOTS.SHOULDER,
    type: TYPES.LEATHER,
    level: 23,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.SPELL_POWER]: 14,
      [STATS.MAGIC_RESIST]: 0.79,
      [STATS.MANA_REGEN]: 0.16,
      [STATS.ARMOR]: 3,
      [STATS.LIFE]: 35,
      [STATS.ATTACK_POWER]: 5,
      [STATS.ENERGY]: 4,
    },
  },
  {
    name: 'Belt of the Spellflinger',
    desc: '',
    slot: SLOTS.BELT,
    type: TYPES.CLOTH,
    level: 23,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.SPELL_POWER]: 11,
      [STATS.SPELL_CRIT_CHANCE]: 1.37,
      [STATS.ARMOR]: 2,
      [STATS.SPELL_CRIT_POWER]: 11.77,
      [STATS.ENERGY]: 3,
    },
  },
  {
    name: 'Brightened Leggings',
    desc: '',
    slot: SLOTS.LEGS,
    type: TYPES.CLOTH,
    level: 23,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.SPELL_POWER]: 14,
      [STATS.MANA_REGEN]: 0.16,
      [STATS.ARMOR]: 4,
      [STATS.LIFE]: 35,
      [STATS.ENERGY]: 3,
    },
  },
  {
    name: 'Quiver of Plentiful Arrows',
    desc: '',
    slot: SLOTS.OFFHAND,
    type: TYPES.QUIVER,
    level: 23,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.ATTACK_CRIT_POWER]: 6.27,
      [STATS.ATTACK_POWER]: 23,
      [STATS.AGILITY]: 6,
      [STATS.ATTACK_CRIT_CHANCE]: 1.33,
    },
  },
  {
    name: 'Gut Spiller',
    desc: '',
    slot: SLOTS.OFFHAND,
    type: TYPES.DUAL_DAGGER,
    level: 23,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.MANA]: 29,
      [STATS.SPELL_POWER]: 7,
      [STATS.LIFE]: 19,
      [STATS.ATTACK_POWER]: 23,
      [STATS.AGILITY]: 6,
    },
  },
  {
    name: 'Cranium Splitter',
    desc: '',
    slot: SLOTS.OFFHAND,
    type: TYPES.DUAL_AXE,
    level: 23,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.MANA]: 29,
      [STATS.POWER]: 6,
      [STATS.LIFE]: 19,
      [STATS.ATTACK_POWER]: 23,
    },
  },
  {
    name: 'Towering Escutcheon',
    desc: '',
    slot: SLOTS.OFFHAND,
    type: TYPES.SHIELD,
    level: 23,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.BLOCK]: 5.36,
      [STATS.ARMOR]: 11,
      [STATS.POWER]: 6,
    },
  },
  {
    name: 'Luminescent Orb',
    desc: '',
    slot: SLOTS.OFFHAND,
    type: TYPES.WAND,
    level: 23,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.SPELL_POWER]: 21,
      [STATS.SPELL_CRIT_CHANCE]: 1.33,
      [STATS.SPELL_CRIT_POWER]: 6.27,
      [STATS.ENERGY]: 5,
    },
  },
  {
    name: 'Sacred Texts',
    desc: '',
    slot: SLOTS.OFFHAND,
    type: TYPES.BOOK,
    level: 23,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.MANA]: 29,
      [STATS.SPELL_POWER]: 21,
      [STATS.LIFE]: 19,
      [STATS.ENERGY]: 5,
    },
  },
  {
    name: 'Pendant of the Elephant',
    desc: '',
    slot: SLOTS.NECK,
    type: TYPES.ACCESSORY,
    level: 23,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.LIFE]: 152,
      [STATS.LIFE_REGEN]: 1.45,
    },
  },
  {
    name: 'Wooden Statuette',
    desc: '',
    slot: SLOTS.OFFHAND,
    type: TYPES.IDOL,
    level: 23,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.POWER]: 13,
      [STATS.AGILITY]: 13,
      [STATS.ENERGY]: 11,
    },
  },
  {
    name: 'Devil\'s Lament',
    desc: 'Even the deadliest evil of the world may shed a tear...',
    slot: SLOTS.OFFHAND,
    type: TYPES.DUAL_DAGGER,
    level: 31,
    quality: QUALITIES.RELIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.UVX,
    },
    stats: {
      [STATS.ATTACK_POWER]: 40,
      [STATS.SPELL_POWER]: 37,
    },
    special: {
      [HEROES.RANGER]: 'Increases Attack Power by 45. This bonus increases as this item is forged.',
      [HEROES.SHADOWBLADE]: 'Add 25AP and 25SP bonus to Shadow Form for all allies.',
      [HEROES.PHANTOM_STALKER]: 'Increases Remorseless Strike\'s damage by 35%. Remorseless Strike also heals Phantom Stalker for 5% of the damage done, or 20% if Bloody Stance is talented.',
      [HEROES.VENOMANCER]: 'Toxic Nail inflicts 3 stacks per cast.',
    }
  },
  {
    name: 'Quadforce',
    desc: 'This was an essential part of universe\'s most powerful magus.',
    slot: SLOTS.SHOULDER,
    type: TYPES.CLOTH,
    level: 31,
    quality: QUALITIES.RELIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.UVX,
    },
    stats: {
      [STATS.ARMOR]: -36,
      [STATS.MOVE_SPEED]: -12,
      [STATS.SPELL_POWER]: 24,
      [STATS.MANA]: 125,
      [STATS.MANA_REGEN]: 0.49,
      [STATS.MAGIC_RESIST]: 4.61,
    },
    special: {
      [HEROES.ARCANIST]: 'Increases Unstable Power\'s duration by 50%.',
      [HEROES.HYDROMANCER]: 'Increases the radius and the force of Waterspout by 100%.',
      [HEROES.PYROMANCER]: 'Pyromancer has 35% chance to summon one more meteor instead of one.',
      [HEROES.CHRONOWARPER]: 'Astral Form, if the appropriate talent is learned, no longer consumes mana for its Spatial Sever procs.',
    }
  },
  {
    name: 'Night\'s Edge',
    desc: 'Utilize the power of the moon!',
    slot: SLOTS.CHEST,
    type: TYPES.MITHRIL,
    level: 31,
    quality: QUALITIES.RELIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.UVX,
    },
    stats: {
      [STATS.POWER]: 15,
      [STATS.DAMAGE]: 20,
      [STATS.ARMOR]: 36,
      [STATS.SPELL_POWER]: 28,
      [STATS.MANA_REGEN]: -0.77,
      [STATS.DODGE]: 4.22,
      [STATS.GOLD]: 3.43,
    },
    special: {
      [HEROES.DRUID]: 'Barkskin grants a shield that reduces all incoming damage by 50%, to a limit of 1.5 * HeroLevel.',
      [HEROES.PALADIN]: 'Divine Touch can only be cast on enemies. Increases Divine Touch damage by 50%. Divine Touch taunts the target.',
      [HEROES.MEDICASTER]: 'Last Chance will now leave 35% HP instead of 1 when activating.',
    }
  },
  {
    name: 'Corselet of Mars',
    desc: 'Are you ready for a grand battle?',
    slot: SLOTS.CHEST,
    type: TYPES.MITHRIL,
    level: 31,
    quality: QUALITIES.RELIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.UVX,
    },
    stats: {
      [STATS.POWER]: 20,
      [STATS.DAMAGE]: 20,
      [STATS.ARMOR]: 36,
      [STATS.ATTACK_SPEED]: 12.20,
      [STATS.MOVE_SPEED]: -26,
      [STATS.ATTACK_POWER]: 28,
      [STATS.BLOCK]: 3.19,
      [STATS.EXP]: 2.06,
    },
    special: {
      [HEROES.BARBARIAN]: 'Berserker Rage triggers every 5 attacks instead of 8.',
      [HEROES.DRUID]: 'Howl also decreases enemies\' attack damage by 5% and their attack speed by 25%.',
      [HEROES.WARRIOR]: 'Shield Slam adds 20+Level armor for 2 seconds if in Defensive Stance. If in Aggressive Stance, increases the duration of Improved Shield Slam\'s bonus critical power to 3 seconds.',
    }
  },
  {
    name: 'Gloves of Peace',
    desc: 'Under the silent moon, it grants inner peace.',
    slot: SLOTS.GLOVES,
    type: TYPES.MITHRIL,
    level: 31,
    quality: QUALITIES.RELIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.KARRIX,
      kill: BOSS_TYPES.UVX,
    },
    stats: {
      [STATS.ENERGY]: 38,
      [STATS.LIFE_REGEN]: 7.12,
      [STATS.MANA_REGEN]: 0.81,
      [STATS.MOVE_SPEED]: -37,
      [STATS.ATTACK_CRIT_CHANCE]: 5.23,
      [STATS.SPELL_CRIT_CHANCE]: 5.23,
      [STATS.MAGIC_RESIST]: 0.98,
    },
    special: {
      [HEROES.AEROMANCER]: 'Electrolysis has 1.3x the chance to trigger on enemies that cannot be instakilled (instakill chance remains the same).',
      [HEROES.SHADOW_SHAMAN]: 'Shadow Totem has a 10% chance to heal nearby allies.',
    }
  },

  // AVNOS
  {
    name: 'Burly Steel Pauldrons',
    desc: '',
    slot: SLOTS.SHOULDER,
    type: TYPES.MAIL,
    level: 25,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.SPELL_POWER]: 2,
      [STATS.MAGIC_RESIST]: 1.40,
      [STATS.ARMOR]: 12,
      [STATS.POWER]: 5,
      [STATS.LIFE]: 29,
      [STATS.ATTACK_POWER]: 8,
    },
  },
  {
    name: 'Angry Steel Belt',
    desc: '',
    slot: SLOTS.BELT,
    type: TYPES.MAIL,
    level: 25,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.ATTACK_CRIT_POWER]: 9.71,
      [STATS.SPELL_POWER]: 3,
      [STATS.MAGIC_RESIST]: 1.40,
      [STATS.ARMOR]: 3,
      [STATS.POWER]: 6,
      [STATS.ATTACK_POWER]: 11,
      [STATS.ATTACK_CRIT_CHANCE]: 1.37,
    },
  },
  {
    name: 'Holy Steel Gauntlets',
    desc: '',
    slot: SLOTS.GLOVES,
    type: TYPES.MAIL,
    level: 25,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.SPELL_POWER]: 15,
      [STATS.MAGIC_RESIST]: 1.40,
      [STATS.MANA_REGEN]: 0.17,
      [STATS.ARMOR]: 3,
      [STATS.LIFE]: 37,
      [STATS.ATTACK_POWER]: 5,
      [STATS.ENERGY]: 3,
    },
  },
  {
    name: 'Cutthroat\'s Leather Slacks',
    desc: '',
    slot: SLOTS.LEGS,
    type: TYPES.LEATHER,
    level: 25,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.ATTACK_CRIT_POWER]: 8.90,
      [STATS.SPELL_POWER]: 4,
      [STATS.MAGIC_RESIST]: 0.84,
      [STATS.ARMOR]: 5,
      [STATS.ATTACK_POWER]: 12,
      [STATS.AGILITY]: 6,
      [STATS.ATTACK_CRIT_CHANCE]: 1.37,
    },
  },
  {
    name: 'Helm of Balance',
    desc: '',
    slot: SLOTS.HELM,
    type: TYPES.LEATHER,
    level: 25,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.SPELL_POWER]: 15,
      [STATS.MAGIC_RESIST]: 0.84,
      [STATS.MANA_REGEN]: 0.17,
      [STATS.ARMOR]: 4,
      [STATS.LIFE]: 37,
      [STATS.ATTACK_POWER]: 5,
      [STATS.ENERGY]: 3,
    },
  },
  {
    name: 'Neversilk Gloves',
    desc: '',
    slot: SLOTS.GLOVES,
    type: TYPES.CLOTH,
    level: 25,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.SPELL_POWER]: 11,
      [STATS.SPELL_CRIT_CHANCE]: 1.46,
      [STATS.ARMOR]: 2,
      [STATS.SPELL_CRIT_POWER]: 12.54,
      [STATS.ENERGY]: 3,
    },
  },
  {
    name: 'Eversilk Cap',
    desc: '',
    slot: SLOTS.HELM,
    type: TYPES.CLOTH,
    level: 25,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.SPELL_POWER]: 15,
      [STATS.MANA_REGEN]: 0.17,
      [STATS.ARMOR]: 3,
      [STATS.LIFE]: 37,
      [STATS.ENERGY]: 3,
    },
  },
  {
    name: 'Healthy Steel Mantle',
    desc: '',
    slot: SLOTS.SHOULDER,
    type: TYPES.MAIL,
    level: 25,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.MAGIC_RESIST]: 1.40,
      [STATS.ARMOR]: 4,
      [STATS.POWER]: 7,
      [STATS.LIFE]: 74,
    },
  },
  {
    name: 'Healthy Hide Mantle',
    desc: '',
    slot: SLOTS.SHOULDER,
    type: TYPES.LEATHER,
    level: 25,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.MAGIC_RESIST]: 0.84,
      [STATS.ARMOR]: 3,
      [STATS.AGILITY]: 7,
      [STATS.LIFE]: 74,
    },
  },
  {
    name: 'Healthy Woven Mantle',
    desc: '',
    slot: SLOTS.SHOULDER,
    type: TYPES.CLOTH,
    level: 25,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.ARMOR]: 3,
      [STATS.ENERGY]: 7,
      [STATS.LIFE]: 74,
    },
  },
  {
    name: 'Amulet of the Heavens',
    desc: '',
    slot: SLOTS.NECK,
    type: TYPES.ACCESSORY,
    level: 25,
    quality: QUALITIES.ENCHANTED,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.NORMAL,
    },
    stats: {
      [STATS.POWER]: 12,
      [STATS.AGILITY]: 12,
      [STATS.ENERGY]: 14,
    },
  },
  {
    name: 'Brass Knuckles',
    desc: '',
    slot: SLOTS.GLOVES,
    type: TYPES.MAIL,
    level: 25,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.MAGIC_RESIST]: 1.40,
      [STATS.ARMOR]: 3,
      [STATS.ATTACK_POWER]: 52,
    },
  },
  {
    name: 'Godly Gauntlets',
    desc: '',
    slot: SLOTS.GLOVES,
    type: TYPES.MAIL,
    level: 25,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.SPELL_POWER]: 47,
      [STATS.ARMOR]: 3,
      [STATS.ATTACK_POWER]: 52,
    },
  },
  {
    name: 'Cutthroat\'s Gloves',
    desc: '',
    slot: SLOTS.GLOVES,
    type: TYPES.LEATHER,
    level: 25,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.MAGIC_RESIST]: 0.84,
      [STATS.ARMOR]: 3,
      [STATS.ATTACK_POWER]: 52,
    },
  },
  {
    name: 'Spider-woven Gloves',
    desc: '',
    slot: SLOTS.GLOVES,
    type: TYPES.LEATHER,
    level: 25,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.MAGIC_RESIST]: 0.84,
      [STATS.ARMOR]: 3,
      [STATS.SPELL_POWER]: 47,
    },
  },
  {
    name: 'Spelled Satin Ribbon',
    desc: '',
    slot: SLOTS.GLOVES,
    type: TYPES.CLOTH,
    level: 25,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.ARMOR]: 2,
      [STATS.SPELL_POWER]: 47,
    },
  },
  {
    name: 'Striker\'s Leggings',
    desc: '',
    slot: SLOTS.LEGS,
    type: TYPES.MAIL,
    level: 25,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.ARMOR]: 6,
      [STATS.DAMAGE]: 34,
      [STATS.ATTACK_SPEED]: 23.31,
      [STATS.MAGIC_RESIST]: 1.40,
    },
  },
  {
    name: 'Stabber\'s Pantaloon',
    desc: '',
    slot: SLOTS.LEGS,
    type: TYPES.LEATHER,
    level: 25,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.ARMOR]: 5,
      [STATS.DAMAGE]: 29,
      [STATS.ATTACK_SPEED]: 23.31,
      [STATS.MAGIC_RESIST]: 0.84,
    },
  },
  {
    name: 'Fool\'s Legwear',
    desc: '',
    slot: SLOTS.LEGS,
    type: TYPES.CLOTH,
    level: 25,
    quality: QUALITIES.EPIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.VX,
    },
    stats: {
      [STATS.ARMOR]: 4,
      [STATS.DAMAGE]: 43,
      [STATS.ATTACK_SPEED]: 23.31,
    },
  },
  {
    name: 'Faceless Mask',
    desc: 'It drains endless life energy.',
    slot: SLOTS.HELM,
    type: TYPES.MITHRIL,
    level: 33,
    quality: QUALITIES.RELIC,
    source: {
      type: SOURCES.BOSS,
      id: BOSSES.AVNOS,
      kill: BOSS_TYPES.UVX,
    },
    stats: {
      [STATS.POWER]: 20,
      [STATS.MANA]: 81,
      [STATS.MOVE_SPEED]: 43,
      [STATS.DODGE]: 2.96,
      [STATS.BLOCK]: 2.83,
    },
    special: {
      [HEROES.ALL]: '25% chance to negate any magic damage. When damage is negated by this effect, recover Mana equal to 3% of the negated damage or 10 Mana, whichever is lower.'
    }
  },
]